POST http:localhost:8080/products HTTP/1.1
Content-Type: application/json
{
    "name": "Product Test 5",
    "price": 123.45,
    "quantity": 321
}

###
GET http:localhost:8080/products/dd2e69e6-30db-4c62-bee2-086bb31a7d77	 HTTP/1.1
Content-Type: application/json

###
PUT http:localhost:8080/products/37938ad7-7a32-4d56-9761-38f3f81c5536	 HTTP/1.1
Content-Type: application/json
{
    "name": "Product Test Updated",
    "price": 54321.12,
    "quantity": 123
}


###
DELETE http:localhost:8080/products/dd2e69e6-30db-4c62-bee2-086bb31a7d77	 HTTP/1.1


###

GET http:localhost:8080/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQ2ODExMDEsInN1YiI6ImFkMTAwMjQxLTkzOTMtNDI2Yy04YjU5LTZiOTc5OWY3MzZlMyJ9.GYOzdk6Vf45coyVRdu4eunGhPM3O6jzZDaz74Qw0-5E

###

GET http:localhost:8080/products?page=1&limit=3 HTTP/1.1