// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/luizhenrique-dev/go-products-api/infra/database"
	"github.com/luizhenrique-dev/go-products-api/internal/usecase/product"
	"gorm.io/gorm"
)

import (
	_ "github.com/luizhenrique-dev/go-products-api/docs"
)

// Injectors from wire.go:

func NewCreateProductUseCase(db *gorm.DB) *usecase.CreateProductUC {
	productRepository := database.NewProductRepository(db)
	createProductUC := usecase.NewCreateProductUC(productRepository)
	return createProductUC
}

// wire.go:

var setRepositoryDependency = wire.NewSet(database.NewProductRepository, wire.Bind(new(database.ProductRepositoryInterface), new(*database.ProductRepository)))
